Feature/6 adding new pet
best-for-beast/app.bestforbeast.com pull request #17
Opened 2020-11-19 13:24 UTC by marcingolenia

2020-11-22 20:38 UTC, sgraczyk commented on .eslintrc.js
> +    'no-unused-vars': 'warn',
Is there a specific reason for that? Is this a common case in which requires rule change or can we handle it by disabling ESLint per case (line)?

2020-11-22 20:40 UTC, sgraczyk commented on .github/workflows/code-analysis.yml
> +        run:  npm run test -- --coverage
We're already running tests in a separate workflow. Consider removing the other one to avoid duplication.

2020-11-22 20:41 UTC, sgraczyk commented on .github/workflows/code-analysis.yml
> +        run:  sudo npm install -g jest
Why is this required here, while the other workflow does not require it?

2020-11-22 20:41 UTC, sgraczyk commented on README.md
> +[![Bugs](https://sonarcloud.io/api/project_badges/measure?project=best-for-beast_app.bestforbeast.com&metric=bugs)](https://sonarcloud.io/dashboard?id=best-for-beast_app.bestforbeast.com)
Nice. Consider moving it above `## Frontend application for bestforbeast.com`

2020-11-22 20:43 UTC, sgraczyk commented on jest.config.js
> +  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
Can we follow the `kebab-case` rule which is more common for JS/TS filenames?
And consider putting all test/jest related files within the `jest` directory (or rename it to `tests` if you feel it's better.

2020-11-22 20:45 UTC, sgraczyk commented on package.json
> +    "clear_jest": "jest --clearCache",
Consider following the script naming that was already introduced (`lint-fix`, `format-fix`). In general, there are two options:
- `test-clear`
- `test:clear`

2020-11-22 20:46 UTC, sgraczyk commented on package.json
> +    "node-fetch": "^2.6.1",
Where is it used?

2020-11-22 20:47 UTC, sgraczyk commented on sonar-project.properties
> +sonar.exclusions=**/*spec.ts, mocks/**, jest/**, assets/**, src/setupTests.ts
After moving `src/setupTests.ts` to `jest` you can avoid excluding a single file.

2020-11-22 20:47 UTC, sgraczyk commented on src/assets/svg/dog-and-cat.svg
> -<svg enable-background="new 0 0 512 512" version="1.1" viewBox="0 0 512 512" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
👍

2020-11-22 20:48 UTC, sgraczyk commented on src/assets/svg/file-upload.svg
> +</svg>
AFAIR it's better to have a `line break` at EOF, although not a strict rule.

2020-11-22 20:48 UTC, sgraczyk commented on src/mocks/data/pets.ts
> +export const IdForPet = 'b6c8872b-2f63-4511-966e-a691c30018d4'
Why not?:

```suggestion
export const PetId = 'b6c8872b-2f63-4511-966e-a691c30018d4'
```

2020-11-22 20:51 UTC, sgraczyk commented on src/mocks/data/pets.ts
> +  'https://www.contentqueens.co.uk/media/1118/tuna.jpg?width=500&height=281.05263157894734'
It just hit me, that we should verify if we're allowed to use all those images. Especially later. For now, it should be fine, as long as it's a mocked data.

2020-11-22 20:52 UTC, sgraczyk commented on src/mocks/data/pets.ts
> +export const ImageUrlForPet =
As above.

Plus, exported constants should follow the `UPPERCASE` naming convention.

2020-11-22 20:53 UTC, sgraczyk commented on src/mocks/handlers.ts
> +  rest.get('http://localhost:5000/api/pets', (_, res, ctx) => {
Why you've just introduced the `localhost` as a hardcoded host? AFAIR it was working without it, especially, that the API should rely on the environment it is using.

2020-11-22 20:55 UTC, sgraczyk commented on src/mocks/handlers.ts
> +      id: IdForPet,
I'm aware it's just a mocked scenario, but we'll get duplicated ids in case of endpoint used multiple times.

2020-11-22 20:56 UTC, sgraczyk commented on src/mocks/node.ts
> +import { setupServer } from 'msw/node'
Actually based on the content it should be named `worker.ts`

2020-11-22 20:57 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +  import { format, getTime } from 'date-fns'
I'm not sure if any sorting rule is configured, but consider moving `external` imports at the top.

2020-11-22 20:59 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetList.svelte
> +  import type { CreatePetDto } from '../../../services/api/pets/contracts'
Sort imports to simplify the maintenance

2020-11-22 21:00 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetList.svelte
> +  import type { CreatePetDto } from '../../../services/api/pets/contracts'
Additionally, I'd consider adding proper exports to `services/api/pets/index.ts` allowing you to export `CreatePetDto` directly from `../../../services/api/pets`

2020-11-22 21:04 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetList.svelte
> +  }
We should establish the rule about `named functions` vs `arrow functions stored in variables`. Usually if not working with `this` context, there's no big need for using arrow functions.

2020-11-22 21:06 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetList.svelte
> +  }
Consider also using some line breaks, especially between functions.

2020-11-22 21:08 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetList.svelte
> +  const createNewPet = async (newPet: CreatePetDto) => {
I think we can omit the `New` word. I guess we don't see a scenario of `creating an old pet`.

2020-11-22 21:12 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetList.svelte
> +  let isPetCreationOn = false
Although it's a simple case, consider following the rule of using `enums` over `booleans`. Especially in the case where you want to define the state of UI/view. I'd go with the local `ViewMode` enum with two options (at least now).

2020-11-22 21:14 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetListItem.svelte
> +  import type { Gender } from '../../../services/api/pets/contracts'
I see that I forgot to place proper export in `index.ts`. Consider shortening this to `../../../services/api/pets`

2020-11-22 21:15 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetListAddItem.svelte
> +        data-testid="add-pet-button"
It's a good practice to store `data-testid` within a constant shareable with tests. Consider moving to the `constants.ts` file or just exporting it from here.

2020-11-22 21:18 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +  export let onCancel: () => void // PR issue - discuss what to do with empty arrow functions (tslint errors). Wanted to assing one here and one below.
You can define a single top-level `noop` const that can be used in such cases to avoid ESLint errors. Usually, utility libraries export such `noop` function.

2020-11-22 21:19 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +  export let onCreate: (newPet: CreatePetDto) => void
`pet` should be enough. Spare your keyboard any additional keystrokes ;)

```suggestion
  export let onCreate: (pet: CreatePetDto) => void
```

2020-11-22 21:20 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +  let birthdate = format(new Date(), 'yyyy-MM-dd')
Is this format valid in the case of all `locales`? Especially for `en-US`?

2020-11-22 21:21 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +      data-testid="create-pet-form"
Consider using const for that.

2020-11-22 21:22 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +        <!--BIRTHDATE-->
Please unify the casing `BIRTHDATE vs Breed`

2020-11-22 21:24 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +        </div>
I know it's just the beginning, but these blocks are very similar. Have you considered creating some reusable blocks. Especially for cases with long class fields.

2020-11-22 21:24 UTC, sgraczyk commented on src/routes/dashboard/pet-list/PetListItem.svelte
> +    data-testid="pet-item-{id}">
Consider using a const for that

2020-11-22 21:25 UTC, sgraczyk commented on src/routes/dashboard/pet-list/helpers.spec.ts
> -
Actually, it was intentional. Can we avoid changing conventions between PRs and establish rules separately?

2020-11-22 21:27 UTC, sgraczyk commented on src/services/api/api-client.ts
> -async function request<T>(url: string, method: HTTPMethod): Promise<T> {
Based on my experience, we'll need a base function covering all methods. There will be numerous scenarios in which we'll do some similar operations/handling.

2020-11-22 21:29 UTC, sgraczyk commented on src/services/api/api-client.ts
> +  await fetch(url, {
Is there any reason why the `post` function is not returning the result? We won't be able to handle the response of any server. We have to keep in mind, some API implementations are going to return the created object with some server-generated data.

2020-11-22 21:31 UTC, sgraczyk commented on src/services/api/pets/contracts.ts
> +export interface CreatePetDto {
`DTO` is an acronym, therefore, we should use all uppercase within names 
```suggestion
export interface CreatePetDTO {
```

2020-11-22 21:32 UTC, sgraczyk commented on src/services/api/pets/contracts.ts
> +export interface PetDto {
What's your opinion on composing DTOs based on some shared structure? Some fields are going to be repeated. I'm aware DRY is not always the best choice, however, this one seems pretty obvious.

2020-11-22 21:33 UTC, sgraczyk commented on src/services/api/pets/pets.ts
> +  post('http://localhost:5000/api/pets', newPet)
As before, why do we need `http://localhost:5000`?

2020-11-22 21:36 UTC, sgraczyk commented on src/setupTests.ts
> +import fetch from 'jest-fetch-mock'
Based on [this](https://github.com/jefflau/jest-fetch-mock#typescript-importing) you can just use 
`import from 'jest-fetch-mock'

2020-11-22 21:36 UTC, sgraczyk commented on src/setupTests.ts
> +/* tslint:disable:no-unused-variable */
AFAIR it can be disabled using `ESLint` comments

2020-11-22 21:36 UTC, sgraczyk commented on src/setupTests.ts
> +import { worker } from './mocks/node'
`src/setupTests.ts` -> `jest/setup-tests.ts`

2020-11-22 21:37 UTC, sgraczyk commented on src/setupTests.ts
> +import fetch from 'jest-fetch-mock'
How is this working in cooperation with `msw`?

2020-11-22 21:37 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +} from '@testing-library/svelte'
External imports over internal imports

2020-11-22 21:38 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +describe('As a pet owner I want to add new pet so I can see it among rest of my pets.', () => {
I'd consider using capital letters for actor name -> `Pet Owner`

2020-11-22 21:39 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +  it('GIVEN pet list WHEN pet owner enters the list THEN no form for adding pet is availible', () => {
I think this could work.

```suggestion
  it(`GIVEN pet list 
        WHEN pet owner enters the list
        THEN no form for adding pet is available`, () => {
```

2020-11-22 21:39 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +    const sut = render(PetList)
What `sut` stands for?

2020-11-22 21:40 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +  const petFormTestId = 'create-pet-form'
Test ids should be shared between tests and components to reduce the cost of maintenance.

2020-11-22 21:41 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +  it('GIVEN pet list WHEN pet owner clicks add new pet THEN A tile with editable form with fields: <Name> required, <Type> required, <Breed>, <Birthdate>, <Gender>, <Description>, <Photo> is added to
Consider formatting as proposed above.

2020-11-22 21:41 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +  it('GIVEN form <Name>, <Birthdate>, <Gender>, <Description> WHEN pet owner creates pet THEN pet can be found in the pet list', async () => {
Consider formatting as proposed above.

2020-11-22 21:42 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +    const birthdate = format(addMonths(new Date(), -ageInMonths), 'yyyy-MM-dd')
We should have that format defined somewhere as a constant.

2020-11-22 21:43 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +    const birthdate = format(addMonths(new Date(), -ageInMonths), 'yyyy-MM-dd')
AFAIR there is `subMonths` function.

2020-11-22 21:44 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +    })
`ids` should be taken from the component.

2020-11-22 21:45 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +import PetList from '../routes/dashboard/pet-list/PetList.svelte'
It's not a component, therefore, follow the `kebab-case` filename convention.

2020-11-22 21:46 UTC, sgraczyk commented on src/tests/PetBrowsing.spec.ts
> +import PetList from '../routes/dashboard/pet-list/PetList.svelte'
It's not a component, therefore, follow the `kebab-case` filename convention.

2020-11-22 21:46 UTC, sgraczyk commented on src/tests/PetBrowsing.spec.ts
> +import { Gender } from '../services/api/pets/contracts'
Sort imports

2020-11-22 21:46 UTC, sgraczyk commented on tailwind.config.js
> +  },
Can you elaborate tomorrow?

2020-11-22 21:47 UTC, sgraczyk commented on tsconfig.json
> -    "noUnusedLocals": true,
I would give up on this that fast. It's very useful.

2020-11-22 21:48 UTC, sgraczyk requested changes
Some very interesting ideas appeared in this PR. I'm afraid that due to the fact that we still have a lot of rules to be established I've left a decent amount of comments to be addressed before merging.

2020-11-22 23:51 UTC, marcingolenia commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +      data-testid="create-pet-form"
For test id? Whats the benefit?

2020-11-22 23:53 UTC, marcingolenia commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +        </div>
Will do. Please first create a commit with reausable block for card which you created for pet item and add pet. I will follow with reusable block after your commit.

2020-11-22 23:58 UTC, marcingolenia commented on src/services/api/api-client.ts
> -async function request<T>(url: string, method: HTTPMethod): Promise<T> {
I don't get it. What is wrong with current implementation?

2020-11-22 23:59 UTC, marcingolenia commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +  export let onCreate: (newPet: CreatePetDto) => void
Will do

2020-11-22 23:59 UTC, marcingolenia commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +  let birthdate = format(new Date(), 'yyyy-MM-dd')
Yes

2020-11-22 23:59 UTC, marcingolenia commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +        <!--BIRTHDATE-->
Will do

2020-11-23 00:01 UTC, marcingolenia commented on src/routes/dashboard/pet-list/helpers.spec.ts
> -
I am not sure what you are referring to....

2020-11-23 00:01 UTC, marcingolenia commented on src/routes/dashboard/pet-list/helpers.spec.ts
> -
The empty line is a problem?

2020-11-23 00:11 UTC, marcingolenia commented on src/services/api/api-client.ts
> +  await fetch(url, {
HTTP POST is a  Command - so an intent to produce side effects. If the service handles the request synchronously, it should return the result of invoking the Command. As you shoul know the result of command should be void in OOP or result in FP. 

If we do POST then  we want a new resource, the REST API should return a 201 (Created) with a proper Location header. That's all described in detail in the RESTful Web Services Cookbook.

2020-11-23 00:20 UTC, marcingolenia commented on src/services/api/pets/contracts.ts
> +export interface CreatePetDto {
Who told you that? In books i have code that have "Dto" in names. Do you know any rules for namig acronyms in your way?

2020-11-23 00:58 UTC, marcingolenia commented on src/tests/PetAdding.spec.ts
> +    const sut = render(PetList)
System under test

2020-11-23 01:02 UTC, marcingolenia commented on src/tests/PetAdding.spec.ts
> +  const petFormTestId = 'create-pet-form'
I don't agree, tests should be independent if you want them to be maintanable.

2020-11-23 01:03 UTC, marcingolenia commented on src/tests/PetAdding.spec.ts
> +  it('GIVEN pet list WHEN pet owner enters the list THEN no form for adding pet is availible', () => {
Do you mean multiline?

2020-11-23 01:04 UTC, marcingolenia commented on src/tests/PetAdding.spec.ts
> +describe('As a pet owner I want to add new pet so I can see it among rest of my pets.', () => {
Is this grammaticaly correct? I don't think so. If it's not whats thw benift? I dont see any.

2020-11-23 01:05 UTC, marcingolenia commented on src/setupTests.ts
> +/* tslint:disable:no-unused-variable */
See tsconfig. Compiler throws the error, not linter.

2020-11-23 01:07 UTC, marcingolenia commented on src/setupTests.ts
> +import fetch from 'jest-fetch-mock'
It works well in other case the tests won't pass would they? The alternative is to use node-fech package but jest-fetch does the work, if we don't configure the mocks

2020-11-23 06:52 UTC, marcingolenia commented on src/setupTests.ts
> +import { worker } from './mocks/node'
Will do

2020-11-23 06:55 UTC, marcingolenia commented on src/tests/PetAdding.spec.ts
> +import PetList from '../routes/dashboard/pet-list/PetList.svelte'
Will do

2020-11-23 07:09 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +  let birthdate = format(new Date(), 'yyyy-MM-dd')
Ok, thanks for the clarification.

2020-11-23 07:10 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +      data-testid="create-pet-form"
If you ever decide to change the `testid` the test will remain unaffected if you share some stable values. And changes do happen.

2020-11-23 07:11 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +        </div>
Ok, I'll try to address it today. If you prefer, we can also move it outside this PR.

2020-11-23 07:13 UTC, sgraczyk commented on src/routes/dashboard/pet-list/helpers.spec.ts
> -
Of course, I don't want to start bikeshedding. Personally, I use line breaks to divide some parts of the code and increase the readability, at least per my perception. I think we can discuss it. In this case, I was referring to the fact, that you've removed the line break.

2020-11-23 07:16 UTC, sgraczyk commented on src/services/api/api-client.ts
> -async function request<T>(url: string, method: HTTPMethod): Promise<T> {
To be discussed within the next block of review comment.

2020-11-23 07:22 UTC, sgraczyk commented on src/services/api/api-client.ts
> +  await fetch(url, {
Even if we agree that `POST` should be treated as a side effect produces, this does not change the fact, that your change silences the response at all. It's a promise-based mechanism which by default should return the result of its operation in order to properly handle both valid results and the thrown error.

Keep in mind it's an API client implementation, and although, we may want to avoid generic mechanisms, this one feels generic in its nature. We cannot simply handle everything using try/catch blocks. AFAIR without the `return`, the try/catch block won't work as expected (I need to confirm it, however).

What I want to emphasize is the fact, that `fetch` has the result on purpose and we cannot just ignore it's there because of some RESTful rules. You should always be ready to handle the server's response, and due to that rules, we're going to ignore it at all.

2020-11-23 07:28 UTC, sgraczyk commented on src/services/api/pets/contracts.ts
> +export interface CreatePetDto {
Ok, I've started some digging, and it looks that I've remembered only half of the rule. By referring to a similar discussion [here](https://stackoverflow.com/questions/15526107/acronyms-in-camelcase) I agree with you that `Dto` is an acceptable form. Only two-letter acronyms or abbreviations should use the `UPPERCASE` form.

I guess it's my personal taste that tells me that I'm butchering the acronym by using lowercase letters.

2020-11-23 07:29 UTC, sgraczyk commented on src/setupTests.ts
> +import fetch from 'jest-fetch-mock'
I'm not sure if I understand correctly, to be discussed.

2020-11-23 07:32 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +describe('As a pet owner I want to add new pet so I can see it among rest of my pets.', () => {
As always - readability, putting an emphasis on something important. Of course, that's more of a discussion of grammar vs system definition. Keep in mind that if you sign some agreements, the most important terms receive a bonus of capital letter at the beginning, it may be not a proper grammar approach, but pretty common practice to improve the readability and discoverability of these terms.

2020-11-23 07:33 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +  it('GIVEN pet list WHEN pet owner enters the list THEN no form for adding pet is availible', () => {
Yes, especially that this is how I've seen most of `BDD` scenarios. GitHub actually processed it a bit strange. Just consider using backticks to format it this way, of course, if you feel it's fine.

2020-11-23 07:34 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +    const sut = render(PetList)
I'm not a fan of variable names that require additional explanation, but if we treat it as a standard I'm fine with that.

2020-11-23 07:35 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +  const petFormTestId = 'create-pet-form'
Why should a change of id cause a test to fail?

2020-11-23 07:36 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +  const petFormTestId = 'create-pet-form'
> tests should be independent if you want them to be maintainable
This is way too general an assumption. There is a very good reason why you keep tests in the same repository as the application code.

2020-11-24 15:14 UTC, marcingolenia commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +      data-testid="create-pet-form"
I am not sure if get it. You want to export that constant from the component and use it in the test? If yes then I am not sure - do we want to expose additional information to production code which are valid in the tests perspective only? I don't think so. It's extra noise, extra lines of code. The other question is why I would want to ever change the test id? Id by definition should not be changed. 

Imagine a class which is not a component, would you make a public variable, method, anything only for testing puproses? I never such thing. If you are 100% sure I would need more explanation on this.

2020-11-24 15:25 UTC, marcingolenia commented on src/routes/dashboard/pet-list/helpers.spec.ts
> -
Peronally I think that empty lines cause bad readibility. I would put it that way; If you want to establish a convention let's first discuss it and agree on the convection and write it down and let's keep such things in README or something. A convention which is not shared to the others is a personal preference.

2020-11-24 15:32 UTC, marcingolenia commented on src/services/api/api-client.ts
> +  await fetch(url, {
I don't see the problem for now. Can we keep the implementation simple and change the implementation if needed?

2020-11-24 15:33 UTC, sgraczyk commented on src/routes/dashboard/pet-list/helpers.spec.ts
> -
I've misused the `convention` word and you're right. I've not proposed a decision to be treated as a convention, yet I wanted to emphasize the fact that the code authored by someone else was changed based on a personal preference. I'd consider doing so based on the discussion and/or rules definition.

2020-11-24 15:37 UTC, marcingolenia commented on src/setupTests.ts
> +import fetch from 'jest-fetch-mock'
The fetch API is not implemented in Node. You need to use an external module for that, like node-fetch, cross-fetch etc. I have selected jest-fetch-mock, because it provides a fetch polyfill and opens up the way to mock a fetch if needed.

2020-11-24 15:42 UTC, marcingolenia commented on src/services/api/pets/pets.ts
> +  post('http://localhost:5000/api/pets', newPet)
Unfortunately we do.
from
https://mswjs.io/docs/getting-started/integrate/node
> Bear in mind that without a DOM-like environment, like the jsdom from Jest, you must use absolute request URLs in NodeJS

2020-11-24 15:45 UTC, marcingolenia commented on src/tests/PetAdding.spec.ts
> +} from '@testing-library/svelte'
Changed. Can we configure linter to do this?

2020-11-24 15:46 UTC, marcingolenia commented on src/tests/PetAdding.spec.ts
> +describe('As a pet owner I want to add new pet so I can see it among rest of my pets.', () => {
I don't see any readibility improvement, I have changed this because I don't care :)

2020-11-24 15:50 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +      data-testid="create-pet-form"
> do we want to expose additional information to production code

At this moment we don't strip `data-testid` from production build (unless it somehow happens under the hood 🤷). If we want to avoid exposing such data to production it is yet to be done. On the other side, there are opinions, that `data-testid` are allowed to be on production, eg. for production-based tests. We should establish what's our plan here. Also, the process of stripping the `data-testId` brings a slight risk of regression, due to some process introducing physical changes between production code and the one developers are working on. This risk is acceptable in this project I guess.

> The other question is why I would want to ever change the test id? Id by definition should not be changed.

It's not about the case in which you want to do so, but when you might need to do so. You might need to change the naming convention, or in the case of E2E testing, your ids became not precise enough causing conflicts. I want to tell you that "things happen", even if you don't want to.

> Imagine a class which is not a component, would you make a public variable, method, anything only for testing puproses? I never did such thing. If you are 100% sure I would need more explanation on this.

I'm not referring to classes, I'm referring to components that are in this case part of the web ecosystem and usually different types of tests. Sharing things like locators, locales, etc. is a common and acceptable practice.

Here's some [explanation](https://techbeacon.com/app-dev-testing/6-reasons-co-locate-your-app-automation-code) by Angie Jones.

2020-11-24 15:53 UTC, sgraczyk commented on src/setupTests.ts
> +/* tslint:disable:no-unused-variable */
In that case, I'd consider using `https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments`

2020-11-24 15:57 UTC, sgraczyk commented on src/services/api/api-client.ts
> +  await fetch(url, {
Yes, we can, however, I think the previous implementation was also quite simple. To be addressed in the future.

2020-11-24 15:58 UTC, sgraczyk commented on src/services/api/pets/pets.ts
> +  post('http://localhost:5000/api/pets', newPet)
Thanks for the clarification.

2020-11-24 15:58 UTC, sgraczyk commented on src/setupTests.ts
> +import fetch from 'jest-fetch-mock'
Ok, now I got it.

2020-11-24 15:59 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +} from '@testing-library/svelte'
I think it's possible, especially that we don't have internal aliases.

2020-11-24 16:01 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +describe('As a pet owner I want to add new pet so I can see it among rest of my pets.', () => {
I guess it's an individual perception. Capital letters catch my attention more quickly.

2020-11-24 16:03 UTC, sgraczyk commented on src/tests/PetAdding.spec.ts
> +  const petFormTestId = 'create-pet-form'
The discussion is held [here](https://github.com/best-for-beast/app.bestforbeast.com/pull/17#discussion_r529667327). Resolving here.

2020-11-24 16:06 UTC, sgraczyk commented on jest.config.js
> +  setupFilesAfterEnv: ['<rootDir>/jest/setupTests.ts'],
```suggestion
  setupFilesAfterEnv: ['<rootDir>/jest/setup-tests.ts'],
```

2020-11-24 16:07 UTC, sgraczyk commented on jest/setupTests.ts
> +import fetch from 'jest-fetch-mock'
I'm still bothered if importing a named version is required. I've sent a link to docs that suggests it's not necessary. Have you checked that?

2020-11-24 16:08 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +        <!--BIRTHDATE-->
Thanks

2020-11-24 16:33 UTC, marcingolenia commented on src/tests/PetAdding.spec.ts
> +  it('GIVEN pet list WHEN pet owner enters the list THEN no form for adding pet is availible', () => {
looks nice!

2020-11-24 16:38 UTC, marcingolenia commented on .eslintrc.js
> +    'no-unused-vars': 'warn',
Not anymore, I've deleted that rule

2020-11-24 18:09 UTC, sgraczyk commented on jest.config.js
> +  setupFilesAfterEnv: ['<rootDir>/jest/setup-tests.ts'],
❤️

2020-11-24 18:09 UTC, sgraczyk commented on .github/workflows/tests-and-code-analysis.yml
> +        run:  sudo npm install -g jest
It can be removed probably

2020-11-24 18:11 UTC, sgraczyk commented on src/mocks/data/pets.ts
> +import { Gender, PetDto } from '../../se../../services/api/pets/contracts'
Something went wrong here :)

2020-11-24 18:12 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +      data-testid="create-pet-form"
The rule around the topic above should've resolved within different PR/decision.

2020-11-24 18:15 UTC, sgraczyk commented on src/routes/dashboard/pet-list/CreatePet.svelte
> +        </div>
I think it's not critical right now. To be addressed in the future.

2020-11-24 18:17 UTC, sgraczyk approved these changes
It was a harsh discussion, but we've made it ;)
Good job!

2020-11-24 18:17 UTC, marcingolenia commented on src/mocks/data/pets.ts
> +import { Gender, PetDto } from '../../se../../services/api/pets/contracts'
:D

2020-11-24 20:48 UTC, merged